### PR TITLE
Create any missing directories in extraction tree

### PR DESCRIPTION
**Pull request by kbruner**
https://github.com/ooyala/tarball-chef-cookbook/issues/7

### CODE REVIEW

**Comment by kbruner** [comment]
@irabinovitch This is passing locally for me.  Looks like some rvm issue on Travis.

**Comment by kbruner** [comment]
Never mind, I needed to update my chefspec tests.  Oddly, it didn't fail until I did a bundle update.

**Comment by irabinovitch** [comment]
@Quanqued  can someone take a look at this PR from @kbruner ?

**Comment by kbruner** [comment]
@edanaher Pinging you, because you're there...

**Pull request merged**
